# AUV8 proc_control parameters
# Alexandre Lamarre - 2022
# Matlab codegen does not support array for rosparam. the array must be declare as string

#*** proc_control update the parameter only when soft kill (mode 0) is selected. ***
#=========================================================================================================

proc_control:
  mpc:
    # Thrusters effort.
    # must be double.
    tmax: 30.0 # max thrust Newton
    tmin: -25.0 # min thrust Newtons
    # MPC horizon
    # See properties section here : https://www.mathworks.com/help/mpc/ref/mpc.html
    # must be integers
    p: 10 # prediction horizon MAX 10
    m: 1 # control horizon (m<=P otherwise crash)
    #=========================================================================================================
    ## MPC gains
    # gains definition : see properties section under weight : https://www.mathworks.com/help/mpc/ref/mpc.html
    # tips for tunning : https://www.mathworks.com/help/mpc/ug/tuning-weights.html
    # must be defined as strings.
    #=========================================================================================================
    gains:
      #MPC Gains Default
      default:
        ov: "70,60,70,90,90,90,90,0,0,0,0,0,0"
        mv: "0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2"
        mvr: "0.1,0.1,0.1,0.1,0.3,0.3,0.3,0.3"

      #MPC Gain Mode 10
      c10:
        ov: "30,30,30,30,45,45,45,0,0,0,0,0,0"
        mv: "0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0"
        mvr: "0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1"

      #MPC Gain Mode 11
      c11:
        ov: "30,30,30,45,45,45,45,0,0,0,0,0,0"
        mv: "0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0"
        mvr: "0.4,0.4,0.4,0.4,0.5,0.5,0.5,0.5"

      #MPC Gain Mode 19
      c19:
        ov: "0,0,0,0,0,0,0,20,20,20,20,20,20"
        mv: "0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2"
        mvr: "0.1,0.1,0.1,0.1,0.3,0.3,0.3,0.3"
      #MPC no dvl Gains
      noDvl:
        mv: "0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2"
  # TargetReached.
  # must be double.
  target_reached:
    linear_tolerance: 0.2 # meters
    angular_tolerance: 0.3 # radians
    time_in_tolerance: 3.0 # seconds
  #=========================================================================================================
  # physical constants
  #
  # The AUV model use the MKS (Meters, Kilograms, Second) standard.
  #=========================================================================================================
  physics:
    # Basic constants
    #---------------------------------------------------------------------------------------------------------
    rho: 998 # kg/m^3
    g: 9.81 # m/s^2
    # AUV Constant
    #---------------------------------------------------------------------------------------------------------
    mass: 43.78 #Kg
    volume: 0.04503 # M^3
    sub_height: .3 # m
    # Inertia tensor matrix define as:
    # Ixx Ixy Ixz
    # Iyx Iyy Iyz
    # Izx Izy Izz
    I: "1.613, 0.008, 0.004, 0.008, 1.613, -0.001, 0.004, -0.001, 2.9030"
    # Center of mass              x     y     z
    rg: "-0.0035, -0.001, 0.008" # distance (m) between center of mass and the geometric center of the sub.
    # Center of boyency           x     y     z
    rb: "0.00, 0.00, -0.004" # distance (m) between center of boyency and the geometric center of the sub.
    # Drag linear constants
    cdl: "20,20,23.3,3.33,2.33,5" # dimensionless
    # Drag quadratic constants
    cdq: "1.17, 1.17, 0.756, 0.167, 0.1, 0.102" # dimensionless
    # Added mass
    added_mass: "-12.4686, -12.6156, -15.7695, 0, 0, 0" # dimensionless
    # thusters definition
    # each row reprensent a thurster and each colunm reprensent an DOF

    # x      y      z    yaw  roll pitch
    thrusters: "0.270, 0.225, 0.0,-45,-90, 0;-0.270, 0.225, 0.0, 45,-90, 0;-0.270,-0.225, 0.0,-45,-90, 0;0.270,-0.225, 0.0, 45,-90, 0;0.180, 0.180, 0.0,  0,  0, 0;-0.180, 0.180, 0.0,  0,180, 0;-0.180,-0.180, 0.0,  0,  0, 0;0.180,-0.180, 0.0,  0,180, 0"

    # Sensors Definition
    #---------------------------------------------------------------------------------------------------------
    # Force dvl ON even when data is invalid
    # (If Set to TRUE, when dvl is lost, kalman filter will assume DVL return 0m/s)
    # (If set to FALSE' when dvl is lost Kalman will use the theorectical model)
    dvl_lost_override: FALSE # Boolean

    # transformation of the DVL frame to body frame
    dvl_rotation: "0.0, 0.0, 3.1415" # rad
    # depth sensor distance according to the geometric center
    depth_pose: "0.0, 0.0, 0.160" # m

    # hydrophones distance acording to auv center
    hydro_pose: "0.0, 0.0, 0.0" # m

    # sonar distance acording to auv center
    sonar_pose: "0.0, 0.0, 0.0" # m

